dev/acf-export.json, page-template-cluster.php
Initial work on the research cluster pages. The pages are _pages_, and not custom post types, so that they can live in the root. To accomplish this, we're using a custom page template with ACF fields targeted to that template.
Changes will be viewable in dev as soon as I'm able to get onto dev.
**Checklist:**
=> Research clusters

dev/acf-export.json, page-template-cluster.php
Adds promotional areas to the research cluster template.
Makes the cluster lead field a repeater so multiple cluster leads can be defined.
Admins/SuperAdmins need to have the ability to insert promotional sections into the research cluster pages on a per-page basis. 
**Checklist:**
=> Research interstitials

dev/acf-export.json, page-template-cluster.php
Removing a bunch of the fields that we're no longer going to be using, along with the associated template markup.
Some of the new fields needed to be added into the acf export, and a bunch of the old ones needed to be removed.
In dev!
**Checklist:**
=> Field cleanup

dev/acf-export.json, includes/cluster-functions.php, page-template-cluster.php
Added social and events sections. Removed the option to add local or external stories to the news section.
Changes can be viewed in dev.
**Checklist:**
=> Additional content

dev/acf-export.json, functions.php, includes/cluster-functions.php, includes/config.php, includes/post-list-functions.php
New Features:
* A `research_clusters` layout for the `ucf-post-list` shortcode has been added.
* Fallback header image settings have been added to the customizer for the research clusters.
Small Changes:
* The name of the research cluster field tabs have been shortened to help them fit on the screen better.
* A short description field has been added to allow for the small blurb above the "Learn more about..." button on the post list layout.
This allows the clusters to be listed without having to provide manual markup for each one on the listing page.
**Checklist:**
=> Clusters post list layout

includes/config.php, template-parts/header_content-title_subtitle.php
Made the text of the clusters link heading editable in the customizer.
**Checklist:**
=> Heading text

dev/acf-export.json, functions.php, includes/cluster-functions.php, includes/header-functions.php, template-parts/header_content-title_subtitle.php
Adds the ability to override the grouping navigation - the "Faculty Research Clusters" link - on all pages, including the faculty cluster pages. I added these fields to the page header fields, so those are now included in the ACF field export.
Future groupings of research are likely to come up, so this will allow a custom link to be added for each grouping, per page.
**Checklist:**
=> Heading link back

dev/acf-export.json, includes/person-functions.php, page-template-cluster.php
New Features:
* The ability to override the heading text above the colleges/centers
* An image field has been added that will add an image above the colleges/centers heading
* Post doc students now show up in the list under their own h2
Changes requested before moving to QA for the client to work on.
**Checklist:**
=> Researchers fields

dev/acf-export.json, page-template-cluster.php
Made the heading on the academics section editable per page.
We want to be able to change it from the default.
**Checklist:**
=> Added adjustable academics heading

single-research_project.php
Added template for Research Projects.
Tested in dev.
**Checklist:**
=> Added Research Project Template

dev/acf-export.json
Added Header fields to the Research CPT
Tested in dev
**Checklist:**
=> Added Header fields to the Research CPT

includes/person-functions.php, page-template-cluster.php
- Incorporated design updates for the section surrounding research projects and publications
- Fixed undefined index notices coming from the Post List SC plugin due to shortcode attributes not being set and passed to `UCF_Post_List_Common::display_post_list()` in `research_get_faculty_list()` and `research_get_postdoc_list()`.
To wrap up features for the initial release and fix bugs.
Reviewed in Dev.
**Checklist:**
=> Research project/publication cleanup

dev/acf-export.json
Added ACF field settings for Sections and People from the UCF WP Theme to the child theme's config; removed unused field group for Colleges taxonomy.
To simplify field definitions and avoid having to port in fields from two separate themes.
Reviewed in Dev.
**Checklist:**
=> Consolidated ACF configs

footer.php, template-parts/footer.php
Removed fourth column in the footer and add css to push the last column to the first column on desktop.
Tested in dev
**Checklist:**
=> Updated footer to move the last column to the first column on desktop

dev/acf-export.json, includes/post-list-functions.php, package-lock.json, src/scss/_clusters.scss, src/scss/style.scss, static/css/style.min.css
Updated the `research_clusters` post-list layout. A border has been added to the bottom of each faculty cluster. Spacing has been added around the content box on each at the xs breakpoint. All of the content boxes have been aligned to the left. The font on the heading has been updated and reduced in size.
The `cluster_short_name` ACF field has been added and the button text has been updated to use the short name if it is set.
We were looking to address a number of readability and page flow issues.
**Checklist:**
=> Post list layout

includes/publication-functions.php, style.css
Updated the research publications to display contributors.
Client request
Tested in DEV
**Checklist:**
=> Added contributors

dev/acf-export.json
Updated permissions to allow editors to modify interstials.
client request
Tested in DEV
**Checklist:**
=> Updated Interstitial Fields permissions to include editors

dev/acf-export.json, page-template-cluster.php
Reduced the minimum number of cluster leads to 0, effectively making the field not required. Updated the template to account for there being no cluster leads.
Not all clusters have leads.
Changes are available to review in dev and qa.
**Checklist:**
=> Hf non required leads

includes/cluster-functions.php, page-template-cluster.php
Updated styles on custom news/pegasus story markup to better match the UCF News plugin/remove link underlines.
Resolves #46 
Tested in Dev.
**Checklist:**
=> Style adjustments post-Athena upgrade

page-template-cluster.php
- Updated cluster template to not display empty email, phone links if the cluster leads' contact info is not set.
- Updated cluster template to not attempt to loop through a curated news article list if it is empty.
Resolves #42 and #24.
Tested in Dev.
**Checklist:**
=> Display bugfixes

template-parts/header-post.php
The logic was updated, now we are pulling the categories of selected posts.
There was a bug in the code where we were showing all the categories that were created, even those that were not selected. Therefore, the category logic was updated to pull and show only those that were selected.
Tested in my local environment. 
**Checklist:**
=> category bug in the header was fixed.
